apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-07-30T17:14:08Z"
  generation: 1
  labels:
    app: reactjs-redux-todo-list-web
  name: reactjs-redux-todo-list-web
  namespace: default
  resourceVersion: "12797"
  uid: 3dd64316-75e1-4301-8377-e2e05e5ff193
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: reactjs-redux-todo-list-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: reactjs-redux-todo-list-web
    spec:
      containers:
      - image: caprilespe/reactjs-redux-todo-list-web:v1
        imagePullPolicy: IfNotPresent
        name: reactjs-redux-todo-list-web
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-07-30T17:14:14Z"
    lastUpdateTime: "2023-07-30T17:14:14Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-07-30T17:14:08Z"
    lastUpdateTime: "2023-07-30T17:14:14Z"
    message: ReplicaSet "reactjs-redux-todo-list-web-7ffbcc69b4" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
